version: '0.1.3-{build}'

environment:
  matrix:
    - BUILD_TYPE: Release
      COMPILER: MinGW
      PLATFORM: Win32
      WITH_MPFR: yes

install:
- set PATH=C:\MinGW\bin;%PATH%
# Rename sh.exe as sh.exe in PATH interferes with MinGW
- rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"

# zlib is needed for libpng
- nuget install zlib-mingw-x86-master -Source https://ci.appveyor.com/nuget/zlib-94hmpf3q011d
- ps: move zlib*\* deps -force
- move deps\libzlibstatic.a deps\libz.a

- nuget install libpng-mingw-x86-master -Version 1.6.18.44 -Source https://ci.appveyor.com/nuget/libpng-7hwq4pmmrc48
- mkdir deps
- ps: move libpng*\* deps -force

build_script:
- mkdir build
- cd build
- cmake -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=C:\MinGW -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ..
- cmake --build . --config %BUILD_TYPE%

artifacts:
  - path: build/frm2png.exe
    name: Windows binary
    type: File

deploy:
  provider: GitHub
  auth_token:
    secure: "WQRWH4fHMtEyK8upN1h+QW3UGhpiCclabCZYFaCjrqIAjglWt7E64rPaSf2unPZz"
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
