version: 0.1.3-{build}
image: Visual Studio 2017
configuration: Release
platform: x86

before_build:
  - nuget restore

build:
  project: frm2png.sln
  verbosity: minimal

artifacts:
- path: Release/frm2png.exe
  name: frm2png.exe
  
deploy:
  provider: GitHub
  auth_token:
    secure: "WQRWH4fHMtEyK8upN1h+QW3UGhpiCclabCZYFaCjrqIAjglWt7E64rPaSf2unPZz"
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
